### ISSUE TITLE
如何加入右边目录？

### ISSUE THREAD

**Issue by HoracceFeng** [kuhung/kuhung.github.io#21]
Hello 谷粒，

最近我在用 github page 做自己的个人主页，发现你的主页右边有每篇文章的章节名显示，很喜欢，但是找不到你实现的具体代码，麻烦能否告知一二？谢谢！

HoracceFeng

**Comment by kuhung** [comment]
@HoracceFeng  这是在主题里面实现的，在文章（如：https://kuhungio.me/about/ ）最下面有标明 Powered by Hugo & LeaveIt。框架采用的是 Hugo，主题是 Leavelt。

**Comment by HoracceFeng** [comment]
明白了，谢谢！

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
